apiVersion: apps/v1 #define a versão
kind: Deployment
metadata:
  name: frontend-deployment
  labels: #também pode ser entendido como tags, são usadas para identificar e organizar recursos no Kubernetes.
    app: frontend

spec:
  
  template:
    metadata:
      name: pod-nginx
      labels:
        env: production
        app: replica-app
        tier: frontend
    spec: #Especificações do conteiner
      containers:
        - name: nginx-container
          image: nginx:latest #define a imagem a ser utilizada
          ports:
            - containerPort: 80

  selector:
    matchLabels:
      env: production # Utilizado para selecionar os pods que correspondem a esse Deployment com base nos rótulos. O Deployment gerenciará apenas os pods que possuem o rótulo env: production.
  replicas: 4 #define o numero de replicas