apiVersion: v1
kind: Service
metadata:
  name: filipes-svc

spec:
  clusterIP: None
  selector:
    app: filipes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 

---

apiVersion: apps/v1

kind: StatefulSet

metadata: 
  name: filipes-sts

spec:
  serviceName: filipes-svc

  replicas: 3

  selector:
    matchLabels:
      app: filipes-app

  template:
    metadata:
      labels:
        app: filipes-app
    spec:
      containers:
        - name: filipes-container
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: filipes-volume
              mountPath: /usr/share/nginx/html
    
  volumeClaimTemplates:
    - metadata:
        name: filipes-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp2  # Tipo de EBS a ser criado na aws
        resources:
          requests:
            storage: 1Gi